import type { PublishedEventListItem } from "@/lib/events/queries";

const now = new Date();
const daysFromNow = (n: number) =>
  new Date(now.getTime() + n * 24 * 60 * 60 * 1000).toISOString();

export const DEMO_EVENTS: PublishedEventListItem[] = [
  {
    id: "demo-001",
    slug: "prospect-park-cleanup",
    title: "Prospect Park Cleanup",
    description: "Join us for a Saturday morning cleanup.",
    starts_at: daysFromNow(3),
    ends_at: daysFromNow(3),
    city: "Brooklyn",
    state: "NY",
    is_virtual: false,
    venue_name: "Prospect Park",
    cover_image_url: "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=800&q=80",
    category: "volunteer",
    attendee_count: null,
    capacity: null,
    status: "published",
    event_causes: [{ cause_id: "c1", causes: { id: "c1", slug: "climate-action", title: "Climate Action" } }],
  },
  {
    id: "demo-002",
    slug: "tenant-rights-101",
    title: "Tenant Rights 101",
    description: "Know your rights workshop with local legal aid partners.",
    starts_at: daysFromNow(5),
    ends_at: daysFromNow(5),
    city: "Queens",
    state: "NY",
    is_virtual: false,
    venue_name: "Jackson Heights Library",
    cover_image_url: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&q=80",
    category: "workshop",
    attendee_count: null,
    capacity: null,
    status: "published",
    event_causes: [{ cause_id: "c2", causes: { id: "c2", slug: "affordable-housing", title: "Affordable Housing" } }],
  },
  {
    id: "demo-003",
    slug: "virtual-phonebank",
    title: "Virtual Phonebank: Voter Registration",
    description: "Help neighbors get registered with a guided call script.",
    starts_at: daysFromNow(2),
    ends_at: daysFromNow(2),
    city: "Online",
    state: "NY",
    is_virtual: true,
    venue_name: null,
    cover_image_url: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&q=80",
    category: "voter",
    attendee_count: null,
    capacity: null,
    status: "published",
    event_causes: [{ cause_id: "c3", causes: { id: "c3", slug: "protect-democracy", title: "Protect Democracy" } }],
  },
  {
    id: "demo-004",
    slug: "school-board-forum",
    title: "School Board Forum Watch Party",
    description: "Watch and discuss the school board forum with educators and parents.",
    starts_at: daysFromNow(7),
    ends_at: daysFromNow(7),
    city: "Manhattan",
    state: "NY",
    is_virtual: false,
    venue_name: "Community Center",
    cover_image_url: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=80",
    category: "education",
    attendee_count: null,
    capacity: null,
    status: "published",
    event_causes: [{ cause_id: "c4", causes: { id: "c4", slug: "public-education", title: "Public Education" } }],
  },
  {
    id: "demo-005",
    slug: "immigration-clinic",
    title: "Immigration Legal Clinic",
    description: "Drop-in clinic with volunteer attorneys (appointment recommended).",
    starts_at: daysFromNow(6),
    ends_at: daysFromNow(6),
    city: "Bronx",
    state: "NY",
    is_virtual: false,
    venue_name: "Legal Aid Office",
    cover_image_url: "https://images.unsplash.com/photo-1555374018-13a8994ab246?w=800&q=80",
    category: "clinic",
    attendee_count: null,
    capacity: null,
    status: "published",
    event_causes: [{ cause_id: "c5", causes: { id: "c5", slug: "immigration-support", title: "Immigration Support" } }],
  },
  {
    id: "demo-006",
    slug: "democracy-meetup",
    title: "Protect Democracy Meetup",
    description: "Monthly meetup to coordinate voter access work.",
    starts_at: daysFromNow(9),
    ends_at: daysFromNow(9),
    city: "Brooklyn",
    state: "NY",
    is_virtual: false,
    venue_name: "Cafe Common",
    cover_image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80",
    category: "meetup",
    attendee_count: null,
    capacity: null,
    status: "published",
    event_causes: [{ cause_id: "c6", causes: { id: "c6", slug: "protect-democracy", title: "Protect Democracy" } }],
  },
];

