// This file is generated by `npm run db:types`.
// It is checked into the repo as a placeholder so imports work before generation.

export type Database = any;

export type Tables<T extends string> = any;
export type TablesInsert<T extends string> = any;
export type TablesUpdate<T extends string> = any;
export type Enums<T extends string> = any;
